### ISSUE TITLE
Could you help upgrade the vulnerble dependency in amazon-codeguru-profiler-for-spark? 

### ISSUE THREAD

**Issue by HelenParr** [amzn/amazon-codeguru-profiler-for-spark#1]
Hi, @xiongbo-sjtu , I'd like to report a vulnerable dependency in **software.amazon.profiler:codeguru-profiler-for-spark:1.0**.
### Issue Description
I noticed that **software.amazon.profiler:codeguru-profiler-for-spark:1.0** directly depends on **org.apache.spark:spark-core_2.12:3.0.0** in the [pom](https://repo1.maven.org/maven2/software/amazon/profiler/codeguru-profiler-for-spark/1.0/codeguru-profiler-for-spark-1.0.pom). However, as shown in the following dependency graph, **org.apache.spark:spark-core_2.12:3.0.0** sufferes from the vulnerability which the C library **zstd(version:1.4.4)** exposed: [CVE-2021-24032](https://nvd.nist.gov/vuln/detail/CVE-2021-24032).
### Dependency Graph between Java and Shared Libraries
![image (12)](https://user-images.githubusercontent.com/103260963/163406323-9640ac2a-a7aa-446d-8431-48e4ad3ee610.png)
### Suggested Vulnerability Patch Versions
**org.apache.spark:spark-core_2.12:3.2.0** (**>=3.2.0**) has upgraded this vulnerable C library `zstd` to the patch version **1.5.0**.

Java build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Java projects. Could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
Helen Parr

**Comment by xiongbo-sjtu** [comment]
Hi Helen,

Thanks for reaching out!

While spark-core has a transient dependency on libzstd-jni.so, we do not package zstd-jni or spark-core libs into our uber jar, as shown [here](https://github.com/amzn/amazon-codeguru-profiler-for-spark/blob/main/pom.xml#L292-L304). To double check, I've run the following command to confirm that.

```
$jar tf target/zstd-jni-1.4.4-3.jar | grep zstd | wc -l
      35
$jar tf target/codeguru-profiler-for-spark-1.0.jar | grep zstd | wc -l
       0
$jar tf target/codeguru-profiler-for-spark-1.0.jar | grep spark | wc -l
       0
```

Please feel free to cross check by downloading [the jar](https://repo1.maven.org/maven2/software/amazon/profiler/codeguru-profiler-for-spark/1.0/) or building one from the source.

Given that, you should not have to worry about the vulnerability as long as you run on Spark 3.2.0 with zstd v1.5.0, since the vulnerability concern is really on what's used by Spark runtime instead of what's used by this plugin lib at build time.

Please feel free to contact me if you have further questions.

Thanks,
Bo
